import { NeuronExplanation } from './NeuronExplanation'
import { useEffect, useMemo, useRef, useState } from 'react'
import type { SceneData } from '../hooks/useSceneData'
import { useStore } from '../lib/store'

export function ScientificInspector({ data }: { data: SceneData }) {
  const { inspector, toggleInspector, sim, hoveredBodyId, setHovered, setView } = useStore()
  const dialog = useRef<HTMLDialogElement>(null)
  const [search, setSearch] = useState('')
  useEffect(() => { if (inspector) dialog.current?.showModal(); else dialog.current?.close() }, [inspector])
  const nodes = data.circuitDoc.nodes
  const selected = nodes.find(n => n.bodyId === hoveredBodyId)
  const inputs = useMemo(() => new Set(Object.values(sim?.result.seeds ?? {}).flat()), [sim])
  const activeIds = useMemo(() => new Set(sim?.result.activations.map(a => a.body_id) ?? []), [sim])
  const matches = useMemo(() => nodes.filter(n => `${n.type ?? ''} ${n.bodyId} ${n.side ?? ''}`.toLowerCase().includes(search.toLowerCase()))
    .sort((a,b) => Number(activeIds.has(b.bodyId)) - Number(activeIds.has(a.bodyId))).slice(0,60), [nodes,search,activeIds])
  const [connectionResult, setConnectionResult] = useState<{id:number;connections:{source:number;target:number;weight:number}[];error?:string}|null>(null)
  useEffect(() => {
    if (!hoveredBodyId || !inspector) return
    const controller = new AbortController()
    fetch(`${import.meta.env.VITE_API_BASE ?? 'http://127.0.0.1:8000/api'}/neurons/${hoveredBodyId}/connections`, {signal:controller.signal})
      .then(async r => { if (!r.ok) throw new Error('Connections unavailable'); return r.json() })
      .then(r => setConnectionResult({id:hoveredBodyId,connections:r.connections}))
      .catch(e => { if (!controller.signal.aborted) setConnectionResult({id:hoveredBodyId,connections:[],error:String(e)}) })
    return () => controller.abort()
  }, [hoveredBodyId,inspector])
  const connections = connectionResult?.id === hoveredBodyId ? connectionResult.connections : []
  const pick = (id: number) => { setHovered(id); setView('brain'); toggleInspector() }
  return <dialog ref={dialog} className="science-dialog" onCancel={e => { e.preventDefault(); toggleInspector() }} onClick={e => { if (e.target === e.currentTarget) toggleInspector() }}>
    <div className="dialog-content"><header><div><div className="eyebrow">SCIENCE & SOURCES</div><h2>A real connectome.<br/>A simplified model.</h2></div><button autoFocus className="close-dialog" aria-label="Close scientific inspector" onClick={toggleInspector}>×</button></header>
    <div className="dataset-scope"><div><b>~166,700</b><span>neurons in the full CNS dataset</span></div><div><b>{nodes.length.toLocaleString()}</b><span>neurons in the loaded full graph</span></div><a href="https://male-cns.janelia.org/media/" target="_blank" rel="noreferrer">Dataset scope ↗</a></div>
    <div className="science-columns"><section><span className="science-badge">REAL DATA</span><h3>The structure is measured.</h3><p>Neuron identities, skeleton coordinates, synaptic connection counts and region meshes come from MaleCNS v1.0, served by Janelia neuPrint. Researchers supplied the reconstructed 3D geometry; NEUROPULSE renders it with its own colors, cameras and shaders.</p><p>{data.circuitDoc.counts.graphNeurons.toLocaleString()} neurons and {data.circuitDoc.counts.graphEdges.toLocaleString()} connections in the complete annotated neuron graph. {data.context?.neuronCount.toLocaleString() ?? 'No'} sampled context skeletons provide the overview; graph computation is not limited to displayed skeletons.</p></section><section><span className="science-badge modeled">MODELED / INFERRED</span><h3>The activity is computed.</h3><p>Activation magnitude, network steps and any possible response come from a simplified propagation model. The moving fronts follow real cable geometry, but their root, direction and speed are illustrative—not measured electrophysiology or exact synaptic locations.</p><p>Inputs start together; explicit repeated or ongoing cues use disclosed illustrative schedules. Exact narrative timing is not reconstructed. The fly shell is contextual artwork. This is not a perfect recreation of a living fly.</p></section></div>
    <details><summary>Reconstruction & model limitations</summary><p>Displayed skeletons are a sampled, simplified overview. Selecting a neuron loads its unpruned, unhealed source skeleton, including all disconnected components. Overview preprocessing may prune short branches and retain only the largest component; the selected full-detail skeleton does neither. Disconnected fragments are never joined. Region surfaces are decimated. Colors at rest identify cells visually; activity colors identify sensory streams.</p><p>{sim?.result.model_note ?? 'Model timing is expressed in discrete propagation steps. A connection in this graph does not by itself establish a causal behavioral response.'}</p><p>{sim?.response.disclaimer}</p><pre>{JSON.stringify({provenance: data.circuitDoc.provenance, transform: data.circuitDoc.transform, policy: data.circuitDoc.policy},null,2)}</pre></details>
    {sim && <details><summary>Evidence for this experience & output</summary>{sim.experience.components.map(c => <section key={c.stimulus}><h3>{c.label} · {c.mapping_quality.replaceAll('_',' ').toLowerCase()}</h3><p>{c.evidence}</p><p>{c.caveat}</p><p>Input body IDs: {c.body_ids.join(', ')}</p></section>)}{sim.response.channels.filter(c=>c.neurons_activated).map(c=><section key={c.key}><h3>{c.label} · {c.neurons_activated} markers reached</h3><p>{c.evidence}</p><p>Evidence tier: {c.evidence_tier.toLowerCase()}. This is not a calibrated probability of behavior.</p></section>)}</details>}
    <section className="neuron-browser"><div className="eyebrow">EXPLORE REAL NEURONS</div><p>Search the {nodes.length.toLocaleString()} dataset IDs in the full catalogue. Up to 60 matches appear, with cells reached in this run first. Anatomy means available to inspect, not activated.</p><input aria-label="Search neurons by cell type or body ID" placeholder="Search cell type or body ID…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="neuron-list">{matches.map(n=><button key={n.bodyId} onClick={()=>setHovered(n.bodyId)} aria-pressed={hoveredBodyId===n.bodyId}><strong>{n.type ?? 'Unassigned type'}</strong><span>{n.bodyId} · {n.side ?? 'side unknown'}</span><small>{inputs.has(n.bodyId) ? 'Direct input' : activeIds.has(n.bodyId) ? 'Downstream active' : 'Anatomy'}</small></button>)}</div>{matches.length === 0 && <p>No matching neuron in the full catalogue.</p>}
    {selected && <div className="selected-details"><h3>{selected.type ?? 'Unassigned type'} <small>bodyId {selected.bodyId}</small></h3><p>{selected.class ?? selected.superclass ?? 'No class annotation'} · side {selected.side ?? 'unavailable'} · predicted neurotransmitter {selected.nt ?? 'unavailable'}</p><p>{inputs.has(selected.bodyId) ? 'Direct input: selected by the experience’s mapped sensory population.' : activeIds.has(selected.bodyId) ? 'Reached downstream through the real graph in this model.' : 'This neuron is part of the full graph; no activation is claimed.'}</p><NeuronExplanation node={selected} sim={sim}/><button className="simulate" onClick={()=>pick(selected.bodyId)}>Load full-detail neuron ↗</button><h4>Strongest incident connections · full graph, real synapse counts</h4>{connectionResult?.id !== hoveredBodyId && <p>Loading connections…</p>}{connectionResult?.id === hoveredBodyId && connectionResult.error && <p>{connectionResult.error}</p>}{connections.map(e=><p className="connection" key={`${e.source}:${e.target}`}>{e.source} → {e.target}<b>{e.weight} synapses</b></p>)}</div>}
    </section><p className="citation">Decorative UI: <a href="https://21st.dev/community/shaders/neuro-noise-sensation-daf72911-8bd3-441e-b749-5486758942ef" target="_blank" rel="noreferrer">Neuro Noise on 21st.dev</a>, implemented with <a href="https://shaders.paper.design/neuro-noise" target="_blank" rel="noreferrer">Paper Shaders</a>. The sidebar texture and ambient lights are artwork, not neuron data.</p><p className="citation">Source: <a href="https://male-cns.janelia.org/" target="_blank" rel="noreferrer">Janelia FlyEM / MaleCNS</a> · <a href="https://neuprint.janelia.org/" target="_blank" rel="noreferrer">neuPrint</a><br/>{data.circuitDoc.provenance.citation}</p></div>
  </dialog>
}
